name: Test Restore on Ubuntu 16

on:
  push:
    branches: [debug, main]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  restore:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:16.04
      options: --cap-add=SYS_PTRACE --security-opt=seccomp=unconfined
      volumes:
        - /node24_217:/node24_217:rw,rshared
        - /node24_217:/__e/node24:ro,rshared

    steps:
      - name: Setup environment
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get -o Acquire::Retries=5 update > /dev/null
          apt-get -o Acquire::Retries=5 -y -q --no-install-recommends install curl xz-utils ca-certificates zstd software-properties-common > /dev/null
          curl -sSL https://github.com/${{ github.repository }}/archive/${{ github.sha }}.tar.gz | tar -xz --strip-components=1
          curl -sL https://archives.boost.io/misc/node/node-v24.15.0-linux-x64-glibc-217.tar.xz | tar -xJ --strip-components 1 -C /node24_217
          echo "=== System ===" && uname -r && ldd --version | head -1
          echo "=== Node 24 ===" && /node24_217/bin/node --version
          echo "Fixing /etc hosts:"
          cat /etc/hosts
          echo "NEW:"
          sed '/::'/d /etc/hosts | tee /tmp/hosts.new
          cat /tmp/hosts.new > /etc/hosts
      - name: Restore cache (no GDB)
        uses: ./
        with:
          path: test-cache
          key: test-cache-14341a6a19a3bade16b0162416e3b788a6f9d340
          restore-keys: test-cache-
